### PR TITLE
edit features

### PR DESCRIPTION
**Pull request by albfan**
This is just a work in progress.

swipe tabs on bug

Now just add textarea for comments, and create the status, attributes and attachments views

relates to #9

### CODE REVIEW

**Comment by albfan** [comment]
Documentation https://www.bugzilla.org/docs/4.4/en/html/api/Bugzilla/WebService/Bug.html#Bug_Creation_and_Modification

Feature "add comment" added. It is not processing errors or reloading only that comment. I guess background for comment should be white to understand it is a editable field.

**Comment by albfan** [comment]
With bug status workflow readed change status features can be implemented easily.

Note: @JohnMHarrisJr any bugzilla jsonrpc server avaliable to check json implementation?

**Comment by JohnMHarrisJr** [comment]
Possibly, if so it'll be my own. I'll check momentarily.

On November 17, 2016 1:30:47 AM EST, Alberto Fanjul <notifications@github.com> wrote:
>With bug status workflow readed change status features can be
>implemented easily.
>
>Note: @JohnMHarrisJr any bugzilla jsonrpc server avaliable to check
>json implementation?

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by JohnMHarrisJr** [comment]
@albfan My Bugzilla install supports jsonrpc. https://bugs.openblox.org/jsonrpc.cgi

**Comment by albfan** [comment]
Status change is ready (tested only on xmlrpc)

maybe https://landfill.bugzilla.org/ can be used for integration test. Once done (and exact response can be collected) mocking is needed to progress agile without break anything.

I know this is not managing errors and implementation sucks, but I do prefer to merge this, publish on markets and refactor later. Let me know your thoughs, but please, don't be rigurous, This feature and all others already merged are high demanding improvements to app, people deserve to use it. I see apps with a beta version. Why not publish like that?    

I will open issues for all mising features and bad implementations.

**Comment by JohnMHarrisJr** [comment]
@albfan I have no problem with a beta release, since the initial one was published on Google Play (I don't remember doing that, but oh well). You can go ahead and merge this yourself as soon as you think it's ready, and I will create and sign a tag with the new version.

**Pull request merged**
